services:
  #web:
  #  build: .
  #  ports:
   #   - "5000:5000"
   # volumes:
   #   - .:/app
  db:
    image: postgres:15
    container_name: dms-cueh-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dmuser
      POSTGRES_PASSWORD: dmpassword
      POSTGRES_DB: dmsdb
    volumes:
      - dms_cueh_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dms-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  dms_cueh_data:
  pgadmin_data: